### ISSUE TITLE
"Show this dialog at startup" text unreadable on dark themes

### ISSUE THREAD

**Issue by DelPoint** [linuxmint/mintwelcome#16]
Hi All,

I've seen a small cosmetic issue with "Show this dialog at startup" text on dark themes. If the theme's background color similar to the text color used for this check-box, then it is hardly readable. To test it: 

- install 'Jet-Gray' theme from here http://cinnamon-spices.linuxmint.com/themes/view/489
- set the theme for 'Controls'
- launch the welcome screen, and check the color of the label "Show this dialog at startup"

I'm not sure, but I think the issue is related to the line **checkbox.override_color(Gtk.StateType.NORMAL, fgcolor)** in *mintWelcome.py* applied for this checkbox.

Note, at first place I've tought it is a theming issue, but I think it is not.

Cheers.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintwelcome/commit/8e6de61766a422810216afd3806c95efa03a5e67
