### ISSUE TITLE
Position of tooltips should be fixed.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/mintwelcome#21]
When you hover over the mouse pointer on link-icon (New features, Documentations, Apps, etc.) the tooltip appears which is too far from the mouse pointer and selected icon.

![welcome screen_010](https://cloud.githubusercontent.com/assets/12819058/20807935/2f1c0bb2-b81a-11e6-823f-23f28df90356.png)

**Comment by Vahan86** [comment]
The issue is existing in Mint 18.1 as well.

**Comment by Vahan86** [comment]
This issue is still relevant to Cinnamon 3.4.3

**Comment by xenopeek** [comment]
The tooltips are handled by Gtk. mintwelcome creates a gtk.IconView object and loads that with the icons and tooltips text to display. The gtk.IconView object handles when and where to display tooltips autonomously.

**Comment by JosephMcc** [comment]
We are also looking at a redesign of the welcome screen which will pretty much kill this issue.
