### ISSUE TITLE
Remove hardcoding of icons

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/mintwelcome#23]
Those icons seems to being hardcoded:
![image](https://cloud.githubusercontent.com/assets/5832930/23329927/7f95f250-fb4b-11e6-9dc5-42ae74ea478c.png)

https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L166
https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L167

https://github.com/numixproject/numix-core/issues/3601

**Comment by JosephMcc** [comment]
I'm pretty sure this in already in our Roadmap to change.
