### ISSUE TITLE
Welcome screen in Guest accout

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintwelcome#27]
Affects Mint 18.2

For every log in into the guest account the welcome screen gets displayed. Most functions there do make no sense, as they are not usable (by design) for the guest, this applies especially all package management related functions. Also the option for not showing again makes no sense, as by design all settings get reverted to default.

I suggest to not show the welcome screen for the guest account.

**Comment by clefebvre** [comment]
Fixed.
