### ISSUE TITLE
missing microcode-update in Update-Manager / differences Linux Mint 18.2 / LMDE(2) - Drivers section (vs. Release Notes)

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mintwelcome#28]
LMDE(2) does not display the Driver-Manager-Entry in the welcome screen (but shows up a Release Note which is missing in the Ubuntu-Version). The root-chause for that seems the missing a Driver-Manager-Feature with the LMDE(2)-version (which - I guess - led to some reasonable replacement for the "hole" - the [release-note link to linuxmint.com](https://www.linuxmint.com/rel_betsy.php))  on the welcome-screen.

_What's more irritating - installing Mint18.2 (*bit, all Display-Manager-flavours - if I do remember right) in a qemu/kvm vm using a i7-host and (Hypervisor-default)-client offers a **intel-microcode**-driver update with the Driver-Manager on the welcome-screen which is **not offered by the Software-Manager** (even at update level 5 - risky / for both LMDE(2) and the 18.2-flavours)._

If the driver (update) is important for users to be placed at this prominent location and
should be installed urgently (what I guess should be the case as microcode-updates contain important processor-bugfixes) => this update should be available at the Update Manager too.

Note: Both flavours LMDE(2) - Mint 18.2 offer the "intel-microcode" package through synaptic.

![screenshot_lmde-2-cinnamon-64bit-microcode-drmgr_2017-07-14_20 45 20](https://user-images.githubusercontent.com/29999282/28226267-0d134902-68c5-11e7-908d-73484ea1477b.png)

![screenshot_mint-18 2-cinnamon-64bit-microcode-drmgr_2017-07-14_20 47 29](https://user-images.githubusercontent.com/29999282/28226277-1ca23cfc-68c5-11e7-8cb1-7c0def4b4dca.png)

Either the LMDE(2)-version should have the Driver Manager too - as the Driver-Manager is a nice tool giving the user the comfort to see all his installed drivers in one place (without the other update noise) in the preferences (hardware section).

  or

it could be a better solution to have a drivers-section in the ?Update?-Manager ((?Software Manager?)  (with lmde(2/**3**) and Mint 18.**3**) thus not splitting installation-relevant information into different pieces/locations.

cheers orcus

**Comment by xenopeek** [comment]
LMDE 2 handles drivers differently from Linux Mint 18.2. Driver Manager isn't available on LMDE 2 for that reason.

The intel-microcode update in Driver Manager talks not about a package update, as the package isn't installed yet, and thus you didn't see it in Update Manager. By installing intel-microcode your Linux Mint installation would during each boot update the processor's microcode. The same thing you can achieve by installing available BIOS update from your motherboard manufacturer; those updates generally also include processor microcode updates. That's what "update" means in that context.
