### ISSUE TITLE
OS Click Preferences - Welcome Screen Mouse

### ISSUE THREAD

**Issue by DeadRingerWeb** [linuxmint/mintwelcome#29]
The Welcome Screen for 18.3 does not abide by the user preferences for single or double clicks on icons.

**Comment by JosephMcc** [comment]
What rules? Where are you setting this rule?

**Comment by DeadRingerWeb** [comment]
File Management Preferences, Behaviour TAB.  The Welcome Screen does not abide by these settings...

**Comment by JosephMcc** [comment]
I thought that was probably what you meant. The file manager prefs effect the file manager only there isn't much we can do about that. The icon views in places like the welcome screen are supposed to activate with single click.

Thanks for the suggestion but this isn't going to change.

**Comment by DeadRingerWeb** [comment]
The team working on file manager, can they not expose a global variable for other applications to read?

**Comment by JosephMcc** [comment]
No. One because it isn't really worth the effort. The file manager you use is completely unrelated to the welcome screen.  Not all file managers have that setting available. It would only work in apps we actually write not any other apps you use so would be horribly inconsistent.
