### ISSUE TITLE
List of keyboard shortcuts

### ISSUE THREAD

**Issue by ssspacez** [linuxmint/mintwelcome#31]
Some people love keyboard shortcuts, as you are improving the Welcome Screen (Mint's blog post), consider this:

- Create a button, "Keyboard Shortcuts" 
- List all the shortcuts(or the main ones) followed by a very short description of what each one does

**Comment by xenopeek** [comment]
Many thanks for contributing to mintwelcome. Your suggestion was reviewed. For more information on our workflow and feature requests, read: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
