### ISSUE TITLE
New Linux Mint logo on Welcome page

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/mintwelcome#38]
Old Linux Mint logo is still shown on Welcome page in Linux Mint 19.3 Cinnamon, though other System "elements" redesigned and feature new logo (Boot menu, Plymouth splash screen, Menu).

![Screenshot from 2019-12-22 17-44-16](https://user-images.githubusercontent.com/12819058/71322859-e9645980-24e5-11ea-9c2c-52d0806a24d2.png)

Would be good to have the new Linux Mint logo on Welcome page as well in order to have consistent look of the System.

**Comment by kolayne** [comment]
I guess, this must be closed
