### ISSUE TITLE
Use traditional user interface

### ISSUE THREAD

**Issue by joaopauloalbq** [linuxmint/mintwelcome#39]
mintwelcome should use traditional user interface like mintupgrade [[1](https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html)]

![mintupgrade2](https://user-images.githubusercontent.com/9905202/71769166-41df2200-2efc-11ea-8e0a-68787b761b01.png)

**Comment by xenopeek** [comment]
Thanks for submitting your idea for the Welcome Screen. For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
