### ISSUE TITLE
Backwards compatible move of ~/.linuxmint to ~/.config/linuxmint (XDG Base Spec)

### ISSUE THREAD

**Issue by NaoPross** [linuxmint/mintwelcome#43]
I have noticed that the `~/.linuxmint` path is hardcoded, I'd be nice if we could have a minimal compliance with the [XDG base spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to free up a few rows when running `ls -al ~/`.

I've made a little patch to provide this functionality. EDIT: forgot how to python3.
```patch
From f9e926629d615c09c7a4f8b861a0d70361c38d2b Mon Sep 17 00:00:00 2001
From: Nao Pross <naopross@thearcway.org>
Date: Tue, 9 Jun 2020 14:29:26 +0200
Subject: [PATCH] Add support for XDG base spec

---
 usr/bin/mintwelcome-launcher                 | 11 +++++++++--
 usr/lib/linuxmint/mintwelcome/mintwelcome.py |  8 +++++++-
 2 files changed, 16 insertions(+), 3 deletions(-)

diff --git a/usr/bin/mintwelcome-launcher b/usr/bin/mintwelcome-launcher
index 5e2071f..6e9188e 100755
--- a/usr/bin/mintwelcome-launcher
+++ b/usr/bin/mintwelcome-launcher
@@ -3,7 +3,14 @@
 import os
 import xapp.os
 
-flag_path = os.path.expanduser("~/.linuxmint/mintwelcome/norun.flag")
+NORUN_FLAG = os.path.expanduser("~/.linuxmint/mintwelcome/norun.flag")
 
-if (not os.path.exists(flag_path)) and (not xapp.os.is_live_session()) and (not xapp.os.is_guest_session()):
+# XDG Base spec compliance, if available
+if os.environ.get("XDG_CONFIG_HOME"):
+    NORUN_FLAG = os.path.expanduser("%s/mintwelcome/norun.flag" % os.environ.get("XDG_CONFIG_HOME"))
+elif os.path.exists(os.path.expanduser("~/.config")):
+    NORUN_FLAG = os.path.expanduser("~/.config/linuxmint/mintwelcome/norun.flag")
+
+
+if (not os.path.exists(NORUN_FLAG)) and (not xapp.os.is_live_session()) and (not xapp.os.is_guest_session()):
     os.system("mintwelcome")
diff --git a/usr/lib/linuxmint/mintwelcome/mintwelcome.py b/usr/lib/linuxmint/mintwelcome/mintwelcome.py
index 9aa9fe9..e968c1e 100755
--- a/usr/lib/linuxmint/mintwelcome/mintwelcome.py
+++ b/usr/lib/linuxmint/mintwelcome/mintwelcome.py
@@ -12,6 +12,12 @@ from gi.repository import Gtk, Gio, Gdk, GdkPixbuf
 
 NORUN_FLAG = os.path.expanduser("~/.linuxmint/mintwelcome/norun.flag")
 
+# XDG Base spec compliance, if available
+if os.environ.get("XDG_CONFIG_HOME"):
+    NORUN_FLAG = os.path.expanduser("%s/mintwelcome/norun.flag" % os.environ.get("XDG_CONFIG_HOME"))
+elif os.path.exists(os.path.expanduser("~/.config")):
+    NORUN_FLAG = os.path.expanduser("~/.config/linuxmint/mintwelcome/norun.flag")
+
 # i18n
 gettext.install("mintwelcome", "/usr/share/linuxmint/locale")
 from locale import gettext as _
@@ -184,7 +190,7 @@ class MintWelcome():
             if os.path.exists(NORUN_FLAG):
                 os.system("rm -rf %s" % NORUN_FLAG)
         else:
-            os.system("mkdir -p ~/.linuxmint/mintwelcome")
+            os.system("mkdir -p %s" % os.path.dirname(NORUN_FLAG))
             os.system("touch %s" % NORUN_FLAG)
 
     def on_dark_mode_changed(self, button, state):
-- 
2.17.1


```

**Comment by clefebvre** [comment]
This part of the spec is largely ignored by other applications. I think the reason for this is that it's not convenient to separate configuration, data and other files in distinct places. Take .mozilla for instance, they opted for a single directory. Making a backup of this gathers the whole user state of the app, which is handy, if you were to only backup part of it you could bump into issues.

**Comment by NaoPross** [comment]
I don't understand your argument since here there is only a single file, and backups IMHO are actually easier if you just need to copy `.config` and `.local`. In any case I'm not interested in arguing about this spec. Is there anything wrong with the patch? Or is it just a long way of saying that you won't merge it?

**Comment by xenopeek** [comment]
Looking at the source I think only mintupload (not a default install) and mintmenu (used on MATE) also use the `~/.linuxmint` path.

If those two would also be converted, would this be an acceptable PR?

Here for mintupload:

- https://github.com/linuxmint/mintupload/blob/master/usr/lib/linuxmint/mintupload/mintupload_core.py#L35
- https://github.com/linuxmint/mintupload/blob/master/etc/linuxmint/mintUpload.conf#L11

Here for mintmenu:

- https://github.com/linuxmint/mintmenu/blob/master/usr/bin/mintmenu#L17
- https://github.com/linuxmint/mintmenu/blob/master/usr/share/man/man1/mintmenu.1#L15
- https://github.com/linuxmint/mintmenu/blob/master/usr/lib/linuxmint/mintMenu/plugins/applications.py#L647
- https://github.com/linuxmint/mintmenu/blob/master/usr/lib/linuxmint/mintMenu/plugins/applications.py#L1267

I guess the only trouble with this is the files in those directories will have to be migrated to new directory?

**Comment by NaoPross** [comment]
On 02.12.2020 01:02, Vincent Vermeulen wrote:
> Looking at the source I think only mintupload (not a default install) 
> and mintmenu (used on MATE) also use the `~/.linuxmint` path.

Oh, I didn't know that. Then yes, I understand Lefebvre's stance.

For mintmenu, they are all in code (and man page), which wouldn't be
hard to change (without breaking current installs). Whereas mintupload,
has a config file, which could make the change a little more
complicated, but still absolutely feasible.

> I guess the only trouble with this is the files in those directories 
> will have to be migrated to new directory?

The spec allows for both directories to be present for backwards
compatibility. Only new installs would have the files in
`~/.config/linuxmint`.

I have also noticed that the patch does not work against master, I'll
fix it later this week, and maybe open a PR.

> If those two would also be converted, would this be an acceptable PR?

bump

---
Nao Pross <np@0hm.ch>

**Comment by clefebvre** [comment]
I prefer to keep things in one folder and not split resources and configurations. If you're going to troubleshoot, reset or backup, you're going to have to do it on all the local files. There's no reason to separate the configuration (.config) from the resources (.local). Here in this project we only have one file, but if we decide something like that (and maybe we should, to be consistent), we'll eventually need to apply it to all projects.

To me it makes more sense to have one root folder as opposed to many.

**Comment by NaoPross** [comment]
IMHO in general standardization has a value of its own (for the end user) that is greater than "convenience for the developers", especially in cases like this one where it is both backwards compatible and trivial to implement. Secondly I find that partial adherence to the standard is better than no adherence: everything could be in either `~/.local/share/linuxmint` or `~/.config/linuxmint` if you don't think separating the two makes sense (I think it does).

Finally, maybe it has not been stated clearly enough: the point of the standard is to not to have to think about individual applications. To do a backup the user copies over the established classical standard paths: `~/Desktop`, `~/Documents`, ... (defined by `XDG_DESKTOP_DIR`, etc, in `~/.config/user-dirs.dirs`), and now `~/.config`, `~/.local` (defined by `XDG_CONFIG_DIR`, etc) as well instead of having to search individually `.mozilla`, `.vmware`, etc.
