### ISSUE TITLE
Light/Dark mode slider doesn't save state.

### ISSUE THREAD

**Issue by CTimmerman** [linuxmint/mintwelcome#44]
I set the dark mode, but opening the Welcome Screen and checking the First Steps tab, the slider is set to light despite being dark.

![VirtualBox_Mint Cinnamon_10_12_2020_04_59_10](https://user-images.githubusercontent.com/9662163/101719962-bd4e3980-3aa4-11eb-8075-0ea0a7890b1c.png)

**Comment by clefebvre** [comment]
There's no 1-1 correlation between the current theme and the slider. There are many combinations of themes which are not represented in mintwelcome. The reason we have this page here is just to be able to rapidly set a few of these combinations.

**Comment by CTimmerman** [comment]
"There's no 1-1 correlation between the current theme and the slider." - Then how is it setting the current theme brightness? It could read that same setting to restore the slider state.
