### ISSUE TITLE
[Feature request] Add toggle/enable option for snaps

### ISSUE THREAD

**Issue by WhosyVox** [linuxmint/mintwelcome#51]
In the interest of user choice I believe there should be an option to disable the snapd pin from the welcome screen.

I understand (and agree with) the issues of snaps being embedded into apt packages but if the user wants to use snaps then we should respect it and provide an easy option.

With that said, there's nothing to prevent us from displaying some kind of disclaimer, e.g.
_"Enabling this option may also mean snap packages can be installed when using the normal package manager. These apps may start slower than native packages and will update automatically without your consent."_

**Comment by clefebvre** [comment]
The issue with snap isn't just the APT backdoor, it's the centralized control of the Ubuntu store. This is described to some extent at https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html with links to related announcements and discussions.

Clicking a toggle button is certainly easier than typing a command, though the process is already extremely easy to perform.

What we shouldn't do though, is promote Snap to people who might not even have heard of it in the first place, and bypass the rationale and the explanation of the dangers related to snap when people want to enable it.

In the end of the day, people can enable it, it's easy to do, but there's information at their disposal which doesn't just explain how to enable it, but why it's disabled in the first place.
