### ISSUE TITLE
No switch back from dark in grey mode

### ISSUE THREAD

**Issue by erwn16** [linuxmint/mintwelcome#52]
Start: Grey mode.
From Welcome-Screen|First steps: Switch to Dark mode works perfectly. Switch back does not work because Cinnamon task bar and Cinnamenu remain in dark mode.
Behaviour could be repeated.

System: LM 20.3 upgraded from 20.2, Cinnamon. Task bar is on the right side of the desktop. System is up to date.
![Bildschirmfoto vom 2022-01-15 07-28-45](https://user-images.githubusercontent.com/30397907/149611886-6e6c55a0-83dc-45e8-bd95-bdc21b2bcc49.png)
.

**Comment by clefebvre** [comment]
This is the desired behaviour. The default theme combo is to have a light control theme with a dark panel.
