### ISSUE TITLE
[Feature request] Add in the Welcome Menu again the option to choose the traditonal style taskbar (Desktop Layout)

### ISSUE THREAD

**Issue by tuxfanmatze** [linuxmint/mintwelcome#62]
![Choose-Desktop-Layout](https://github.com/linuxmint/mintwelcome/assets/92763466/8ce82bcb-9c31-4c3b-9cba-3b6048111b34)
If find the old one easer to use and for beginners it is difficult to change and configure the needed applets for the taskbar.

**Comment by Andy2051** [comment]
Another plea for the traditional panel. There has been some discussion on the forum on this. Surely as it was there before it can't be too much effort to put it back. Or at the very least tell us how to implement it ourselves.

**Comment by tuxfanmatze** [comment]
I think the code (mostly python?) is already there in old versions.
The compete with KDE,, LXQt, Mate, Xfce partly  and also some distros which has predefined Desktop Layout Tasklist options like ZorinOS, Mate, Manjaro etc, I highly appreciate to bring this Option back.
And I think its not mich effort.
Maybe someone may extract to code and put it info I skript.

**Comment by clefebvre** [comment]
The traditional layout is just a set of preferences. You can reset it like this:

```
gsettings set org.cinnamon panels-height "['1:27']"
gsettings set org.cinnamon enabled-applets "['panel1:left:0:menu@cinnamon.org', 'panel1:left:1:show-desktop@cinnamon.org', 'panel1:left:2:panel-launchers@cinnamon.org', 'panel1:left:3:window-list@cinnamon.org', 'panel1:right:0:systray@cinnamon.org', 'panel1:right:1:xapp-status@cinnamon.org', 'panel1:right:2:keyboard@cinnamon.org', 'panel1:right:3:notifications@cinnamon.org', 'panel1:right:4:printers@cinnamon.org', 'panel1:right:5:removable-drives@cinnamon.org', 'panel1:right:6:favorites@cinnamon.org', 'panel1:right:7:user@cinnamon.org', 'panel1:right:8:network@cinnamon.org', 'panel1:right:9:sound@cinnamon.org', 'panel1:right:10:power@cinnamon.org', 'panel1:right:11:calendar@cinnamon.org']"
gsettings set org.cinnamon panel-zone-icon-sizes "[{"panelId": 1, "left": 0, "center": 0, "right": 0}]"
```

**Comment by Andy2051** [comment]
Thank you.
