### ISSUE TITLE
Asks for a password twice when installing multimedia codecs

### ISSUE THREAD

**Issue by monsta** [linuxmint/mintwelcome#8]
The first time it asks for a password, then launches Synaptic to update the cache.
Then it shows the dialog asking whether I really want to install mint-meta-codecs, and when I answer "Yes", it asks for a password again, then launches Synaptic to finally install the package.

**Comment by clefebvre** [comment]
Not great, but that's an issue on apturl, not mintwelcome. Unless we trick it with some policy.. and make everyone able to update the cache via apturl..

**Comment by monsta** [comment]
Well I can't file a bug report on apturl since we use older pinned version :smile:
